### ISSUE TITLE
Stockholm.zip just stops processing

### ISSUE THREAD

**Issue by matthiasfeist** [atorger/nvdb2osm#12]
Hi!

I tried to process the quite large file for Stockholm and the process keeps on quitting without any error message.
I really don't know enough about python to properly debug this so I hope you can help out.
Here is the log output of the script run with --debug: [stockholm.log](https://github.com/atorger/nvdb2osm/files/6061377/stockholm.log)
 Maybe that gives you some pointers. I tried to run it on my Mac and on a EC2 Amazon Linux instance. Same result. It sometimes comes a bit further but always exists seemingly in the middle of a process.

**Comment by matthiasfeist** [comment]
Alright, it seems to be memory related...
```Mar  2 08:12:44 ip-172-31-2-150 kernel: Out of memory: Kill process 2682 (python) score 850 or sacrifice child
Mar  2 08:12:44 ip-172-31-2-150 kernel: Killed process 2682 (python) total-vm:1458816kB, anon-rss:831156kB, file-rss:0kB, shmem-rss:0kB
Mar  2 08:12:44 ip-172-31-2-150 kernel: oom_reaper: reaped process 2682 (python), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB```

**Comment by atorger** [comment]
Yeah it probably uses quite a lot of memory. I haven't really measured or thought about optimizing it, I have 64 gigs of RAM on my box and Stockholm ran fine last time I tried, but Stockholm is indeed one of the larger areas...

**Comment by matthiasfeist** [comment]
:) yeah it's a lot of data.
I'm currently working on a project where I want to build on top of your amazing work. I already have a pipeline which can download the whole NVDB catalog once per mont, runs your script on all files and then pushes the resulting .osm files to a website so that mappers can use it without having to fiddle around with python.

The next step in the project is then that I want to try to perform a sort of "visual diff" between the generated .osm files and the current state in open street map. My end goal would be a map that shows where open street map has missing geometry or wrongly tagged highways so that mappers can focus their efforts in the right regions.

And thoughts on that?

**Comment by matthiasfeist** [comment]
Great input thanks a lot!
I'll first get my osm files generation with your script online and ping you then :)

After than I'll start thinking about the diff-ing and your comments above 👍
