### ISSUE TITLE
New file names

### ISSUE THREAD

**Issue by EHakansson** [atorger/nvdb2osm#26]
I tried using the script on a dataset from NVDB downloaded just now but found that the filenames seems to have changed since this code was written. The main file seems to have had the name *NVDB_DKReflinjetillkomst.shp but in the export from NVDB the name is *NVDB_DK_O_43_Reflinjetillkomst.shp. Is this an issue or is there something I'm doing wrong?

**Comment by atorger** [comment]
There is probably an issue, NVDB made a big change to the data files during the spring, but the data was buggy to start with so I didn't update the code but instead waited to see that it was fixed first. Then I moved on to other projects so I never updated the code, and now it's vacation times so I probably won't revisit the code until the autumn.

You can find pre-generated files for every municipality though made in March or something, I don't remember the link now but it should be possible to find.

**Comment by atorger** [comment]
https://nvdb-osm-map-data.s3.eu-north-1.amazonaws.com/index.html#6/64.88/17.93

There's the link with pre-generated files.

**Comment by EHakansson** [comment]
Thanks for the feedback! I gave it a go to try to update the references and I think I was successful, at least I was able to get the script to read the files and run for a couple of minutes before another error occurred. I made a pull request with the changes in case that is helpful for you, if not please just close it.

**Comment by atorger** [comment]
I have now changed a bit how it works with filenames, the län-sized shape file archives are first split into municipalities, where the filenames are simplified, and those simplified filenames are used by the script now. Closing this.
