### ISSUE TITLE
Keep lanes tag even if lanes=2

### ISSUE THREAD

**Issue by matthiasfeist** [atorger/nvdb2osm#28]
Hi.
I have a suggestion to keep the lanes tag even if lanes=2 and not oneway. Code here:
https://github.com/atorger/nvdb2osm/blob/4538761f0f6dcf4fa958697b5baf2f3c6798126b/process_and_resolve.py#L1751

My reasoning because I made 2 observations. Both are not because of a right or wrong way of tagging but they mostly evolve around the UX of editors:
1. The Geometry replace plugin will keep an already existing but wrong lane count when importing when the lane tag is not set. That way it's very easy to keep wrong data.
2. StreetComplete will still ask for lane count and people will set lane=2 for streets. We could make this easier if we just had lane=2-ways in the NVDB import to start with.

What do you think?

**Comment by atorger** [comment]
Yes, we should probably do that. I've also noted that oneway with lanes=1 may be desirable on large roads, as it seems to be always set in current OSM data, so maybe always keep lanes.

**Comment by matthiasfeist** [comment]
I was just checking [the wiki](https://wiki.openstreetmap.org/wiki/Key:lanes) on this issue and I saw that it's stated there that: 
> Although it is advisable to always add the lanes tag to roads with lanes, as usual data will be sometimes missing

I would therefore say that it's actually OK and seems to be wanted to have the lane count explicitly in the tagging all the time.

**Comment by atorger** [comment]
I guess "road with lanes" means roads that have line markings to actually show the lanes, but not unpaved roads.

NVDB has lane info but not for all roads. I think it's only the government maintained roads if I remember correctly. It has also lanes on unpaved roads which then is directly related to width, so it's 2 if the road is wide enough, otherwise 1.

One idea would be to keep NVDB lane info as is, but not make up lane info if it doesn't exist.

**Comment by matthiasfeist** [comment]
if we can figure out that there are no markings, we could tag it accordingly: https://wiki.openstreetmap.org/wiki/Key:lanes#No_lane_markings

but I agree that maybe it's best to keep the info from NVDB as it is...

**Comment by atorger** [comment]
I have committed a patch which keeps lanes=1 and lanes=2 when set by NVDB.

**Comment by matthiasfeist** [comment]
cool.
