### ISSUE TITLE
Stop signs are going crazy

### ISSUE THREAD

**Issue by matthiasfeist** [atorger/nvdb2osm#37]
The object with the green boxes are the new objects from the nvdb script. As you can see, something has gone very wrong with the stop signs. I have seen that before as well with the "give-way" signs and fixed it manually but it happens quite often now on **Ekerö** where I am doing the import right now.
The particular instance happened her: https://www.openstreetmap.org/#map=19/59.36927/17.71217

<img width="659" alt="Screenshot 2021-11-02 at 09 35 37" src="https://user-images.githubusercontent.com/1589740/139812800-5dbc8a17-d116-4ff5-9015-2b8d3ee9dc66.png">

**Comment by atorger** [comment]
Strange, haven't seen it on the areas I have worked with. Likely related to some issue with source data there in Ekerö, but should be quite easy to merge it the script so you don't have to :-). I'll have a look.

**Comment by atorger** [comment]
I've checked the source data. The script takes stop signs from the NVDB layer NVDB-Stopplikt (you can open separate source layers in JOSM from the Ekerö.zip shape archive), and indeed the layer contains three stop signs there, ie it's an error in the source data.

First time I see it so I don't know how common it is. Maybe I shall make a pass to merge these type of features when they are very close and on the same road.

**Comment by matthiasfeist** [comment]
Hmmm. Yeah good question. I think it would be nice if the script would fix it so that even if there's a problem in the source data, it doesn't accidentally get imported.

I'll try to find all the instances in the source data and report an error to NVDB.

**Comment by atorger** [comment]
I'm working on a merge feature now, it makes sense to include it as there are lots of duplicates and such stuff anyway, the data overall is not that "clean".

**Comment by matthiasfeist** [comment]
It seems to happen quite frequently in Stockholms län and not only with with Stop signs but also with the Give Way signs.
So I'm not gonna report this as an error because that's way too much work. 😆 
But it absolutely makes sense to fix this in the script.

This will be a bit challenging in situations like these though: 
<img width="1392" alt="Screenshot 2021-11-02 at 19 11 12" src="https://user-images.githubusercontent.com/1589740/139921604-8b88889a-eba2-4937-82a0-71a5cc3e5e9e.png">

**Comment by atorger** [comment]
I have pushed a fix, haven't tested it on that scenario in the screenshot above though, but I think it should work. It checks for duplicate nodes within an 8 meter radius, and filter out those which are connected to the same way, and keep only one of those. It only looks at stop signs and give way signs.

It might have problems with the above scenario as two of the duplicates are very widely spaced, probably more than 8 meters. If we increase the search range a lot there's a risk that you remove stop sign if it is on the other side of a crossing. You could add in analysis for that though, but it makes the function a bit more complicated. If there's some rare duplicate left maybe it's not too bad.

**Comment by matthiasfeist** [comment]
cool. next time I work in ekerö, I'll run the new version manually and see if it works

**Comment by atorger** [comment]
(I realized that the complicated scenario above should work with the current algorithm as long as the duplicates are no longer than 8 meters apart. If there are stop signs on both sides of a crossing they are either connected to different way segments or have different direction tags and will thus not be mixed up.)

**Comment by atorger** [comment]
I think this works now, right? Closing it. Re-open if it doesn't work for you.
