### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by NKAmapper** [atorger/nvdb2osm#4]
Flott initiativ. Kunne du lage en fast folder der du genererer f.eks. tre forskjellige kommuner etter nye patcher til skriptet? F.eks. en storby, en mindre by og en kommune uten på landet.

Og er det mulig å ha en debug-versjon som inkluderer NVDB-kodene som hører til veisegmentet? Da blir det lettere å se hvordan kodene har blitt brukt i taggingen.

**Comment by atorger** [comment]
Bra idéer! Det är rätt mycket som rör på sig just nu dock, jag patchar varje dag saker jag hittar själv medan jag testar så det dröjer nog en stund innan jag kan titta på detta.
