### ISSUE TITLE
Bug: currently no files can be converted correctly

### ISSUE THREAD

**Issue by matthiasfeist** [atorger/nvdb2osm#40]
At the moment it seems that the script doesn't work with any NVDB files...

**Comment by atorger** [comment]
Yes seems to be related NVDB's change of tagging format for gång and cykelvägar. Most likely a trivial fix, I'll look into it after the holidays.

**Comment by atorger** [comment]
I have now updated it to work with the new GCM format but not tested it on so many municipalities.

I've also remade the cycleway/footway crossing resolving code so it should be a bit better and also work with new GCM format.

The new GCM format is less detailed for better or worse. The only thing I really miss from the old format is that we no longer get sidewalk/trottoar tag, it's just tagged as a regular footway.

**Comment by atorger** [comment]
Another change is that cycleway now contains foot=yes, this is not a tagging change, but I recently became aware that this is required for routing algorithms to route foot over cycleway. In Sweden it is allowed to walk on cycleways, but the routing algorithms does not know that, hence foot=yes is added.

**Comment by matthiasfeist** [comment]
cool. I am starting the pipeline now, so by tomorrow we'll see if it worked :)

**Comment by matthiasfeist** [comment]
Seems to work now. At least most of the kommun were converted
