### ISSUE TITLE
Parking has some questionable values

### ISSUE THREAD

**Issue by matthiasfeist** [atorger/nvdb2osm#41]
Hi.
I am currently importing around this area: https://www.openstreetmap.org/#map=18/64.10740/16.17430 and I noticed that NVDB also has some data on parking spaces.
However the capacity and the operator values are clearly bullshit 😆 
So I was wondering if you think this is a systemic issue, if the data is wrong or interpreted in the wrong way, or if the best way would be to omit these tags.
See here:
<img width="2146" alt="Screenshot 2022-01-03 at 16 57 39" src="https://user-images.githubusercontent.com/1589740/147952315-0eaa444b-735d-4b69-b58d-f71c2ac2da5e.png">

**Comment by atorger** [comment]
I have not looked in many places but at least in some it has been correct :-). Almost all large public parkings are already mapped with more detail than NVDB provides though, so usually I dump that info. I think the interpretation is correct, but NVDB may not that well updated. I would guess that it is best on the parkings which has operator=trafikverket

**Comment by matthiasfeist** [comment]
ok. maybe my issue was an isolated incident then :)
