### ISSUE TITLE
Många taggar BETECKNING

### ISSUE THREAD

**Issue by marsip** [atorger/nvdb2osm#45]
Den felaktiga (?) taggen BETECKNING finns med i flera kommunfiler. 
Jag såg det först i Örebro.osm men taggen finns även med i andra kommuner.

**Comment by atorger** [comment]
https://www.nvdb.se/sv/aktuellt/nyhetsarkiv/2022/nya-och-forandrade-dataprodukter-maj-2022/

Det har nog med detta att göra

**Comment by atorger** [comment]
Jag tror denna är fixad i senaste nu

**Comment by marsip** [comment]
Jag har lokalt genererat flera kommuner i Södermanland (Eskilstuna, Gnesta, Flen) och ingen av dessa har BETECKNING som tagg. Så den här felrapporten kan nog stängas.

**Comment by squeak9** [comment]
Verkar som detta händer nu igen, laddade ner `Arvika.osm` som test och allt har `BETECKNING=None`

**Comment by atorger** [comment]
Ska kolla vid tillfälle närmsta dagarna. Koden är gjord som så att den släpper igenom allt den inte tolkat, med tanken att man ska upptäcka när nåt nytt eller ändring kommer från trafikverket, vilket händer nu och då.

**Comment by atorger** [comment]
Nu ska det vara fixat, tillsammans med lite annat småfix.

**Comment by squeak9** [comment]
Händer igen, laddade ner `ale.osm` som var genererat 28 dagar sedan och det har den taggen. Alla konstiga taggar jag ser:

```
BETECKNING=None
DAGSL=None
Kvarterscykelvag=None
Primar_funktion=None
```

**Comment by atorger** [comment]
Har fixat detta nu. Verkade som de också börjat skriva vissa RIKTNING-taggar med siffervärden istället för textvärden också.
