### ISSUE TITLE
Remove NVDB:RLID?

### ISSUE THREAD

**Issue by atorger** [atorger/nvdb2osm#5]
Keeping the NVDB:RLID tag sometimes cause road segments to be shorter than they otherwise would be, making it more cumbersome to merge with existing geometry.

The reason for NVDB:RLID tag to be there is to have a clear link back to the source data. However, a future update script will have to work with quite advanced geometry matching/snapping anyway, so there may not be much value to keep the NVDB:RLID.

**Comment by NKAmapper** [comment]
I agree. The short segments deviate too much from what is normal in OSM. Also, the RLID might not be correct anymore if a user later merges the segment with a different connected way.

I am using an id similar to RLID to decide which ways should be grouped together when concatenating longer ways, but it is not included in the output.

The [highway_merge](https://github.com/osmno/highway_merge) script is an example of how to generate diffs between NVDB and OSM without having RLID or a similar id.

**Comment by atorger** [comment]
I'll try to make a patch this evening. Or rather I'll try NOT to make a patch during this day, because I need to do some paid work too, ha ha.

**Comment by atorger** [comment]
It's in master branch now.

**Comment by NKAmapper** [comment]
Great. If you also update the Göteborg file then we can see the result :)
