### ISSUE TITLE
Add Karlstad for splitting

### ISSUE THREAD

**Issue by craxgard** [atorger/nvdb2osm#56]
Hej!

Jag har skapat en fil för uppdelning av Karlstad. Jag tror jag har gjort rätt, men kolla gärna för säkerhets skull.
[Karlstad-split.zip](https://github.com/atorger/nvdb2osm/files/12209599/Karlstad-split.zip)

Tack på förhand!

**Comment by atorger** [comment]
Den ser mestadels rätt ut, men det är en icke-stängd linje där, se skärmdump. Ska det vara ytterligare en uppdelning, eller är det en hjälplinje som blivit kvar?
![bild](https://github.com/atorger/nvdb2osm/assets/13962807/77fc2c54-e9e6-49f6-9c59-6ea4bbeec51c)

**Comment by craxgard** [comment]
Jag visste att det var något jag missat, det är en hjälplinje som blivit kvar.
